-- Supabase-ready schema for Spark Writers
-- Run this file in the Supabase SQL editor.
-- It creates additional tables (projects, bids, conversations/messages, portfolio, attachments, tags, writer_skills, notifications)
-- and adds Row Level Security (RLS) policy examples. Modify policies to fit your exact auth/user model.

-- IMPORTANT:
-- 1) This schema assumes you have a `users` table (int primary key) in the same DB.
--    We add an `auth_user_id uuid` column to link to Supabase Auth users (auth.uid()).
-- 2) Create a Supabase Auth user for admin (websitesbrian585@gmail.com) via the Auth UI,
--    then update the corresponding `users` row to set `auth_user_id` to that user's UUID.
-- 3) After running this file, enable Row Level Security (RLS) for the tables and review policies.

-------------------------------
-- Link users table to Supabase Auth
-------------------------------
ALTER TABLE IF EXISTS users
  ADD COLUMN IF NOT EXISTS auth_user_id uuid UNIQUE;

-- make created_at timestamptz for consistency
ALTER TABLE IF EXISTS users ALTER COLUMN created_at TYPE timestamptz USING created_at AT TIME ZONE 'UTC';

-------------------------------
-- Projects
-------------------------------
CREATE TABLE IF NOT EXISTS projects (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id int NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title text NOT NULL,
  description text,
  budget numeric(12,2),
  status text DEFAULT 'open', -- open, assigned, closed, cancelled
  created_at timestamptz DEFAULT now(),
  expires_at timestamptz
);
CREATE INDEX IF NOT EXISTS idx_projects_client ON projects (client_id);

-- enable RLS and policies for projects
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;
-- allow clients to insert projects when their auth uid matches their users.auth_user_id
CREATE POLICY IF NOT EXISTS "Insert own project" ON projects
  FOR INSERT
  WITH CHECK (
    auth.uid() IS NOT NULL
    AND (SELECT auth_user_id FROM users WHERE id = projects.client_id) = auth.uid()
  );
-- allow project owners to update/delete
CREATE POLICY IF NOT EXISTS "Modify own project" ON projects
  FOR UPDATE, DELETE
  USING (
    (SELECT auth_user_id FROM users WHERE id = projects.client_id) = auth.uid()
  );
-- public can select open projects
CREATE POLICY IF NOT EXISTS "Select open projects" ON projects
  FOR SELECT
  USING (status = 'open');

-------------------------------
-- Bids / proposals
-------------------------------
CREATE TABLE IF NOT EXISTS bids (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id bigint NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  writer_id int NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  amount numeric(12,2),
  message text,
  accepted boolean DEFAULT false,
  created_at timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_bids_project ON bids (project_id);
CREATE INDEX IF NOT EXISTS idx_bids_writer ON bids (writer_id);

ALTER TABLE bids ENABLE ROW LEVEL SECURITY;
-- allow writers to insert bids when their auth uid matches
CREATE POLICY IF NOT EXISTS "Insert own bid" ON bids
  FOR INSERT
  WITH CHECK (
    auth.uid() IS NOT NULL
    AND (SELECT auth_user_id FROM users WHERE id = bids.writer_id) = auth.uid()
  );
-- allow writers to view their bids and project owners to view bids for their projects
CREATE POLICY IF NOT EXISTS "Select bids for owner or writer" ON bids
  FOR SELECT
  USING (
    (SELECT auth_user_id FROM users WHERE id = bids.writer_id) = auth.uid()
    OR (SELECT auth_user_id FROM users WHERE id = (SELECT client_id FROM projects WHERE id = bids.project_id)) = auth.uid()
  );
-- allow project owner to accept a bid (update accepted) via update policy
CREATE POLICY IF NOT EXISTS "Update bid by project owner" ON bids
  FOR UPDATE
  USING (
    (SELECT auth_user_id FROM users WHERE id = (SELECT client_id FROM projects WHERE id = bids.project_id)) = auth.uid()
  );

-------------------------------
-- Conversations & Messages
-------------------------------
CREATE TABLE IF NOT EXISTS conversations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id bigint REFERENCES projects(id) ON DELETE SET NULL,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id bigint NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  sender_id int NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  body text NOT NULL,
  created_at timestamptz DEFAULT now(),
  is_read boolean DEFAULT false
);
CREATE INDEX IF NOT EXISTS idx_messages_conv ON messages (conversation_id);

ALTER TABLE conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;

-- allow sending messages only if sender matches auth
CREATE POLICY IF NOT EXISTS "Insert message by sender" ON messages
  FOR INSERT
  WITH CHECK (
    auth.uid() IS NOT NULL AND (SELECT auth_user_id FROM users WHERE id = messages.sender_id) = auth.uid()
  );

-- allow participants to read messages: either the sender, or someone who is the client or writer of the project linked to the conversation
CREATE POLICY IF NOT EXISTS "Select messages for participants" ON messages
  FOR SELECT
  USING (
    (SELECT auth_user_id FROM users WHERE id = messages.sender_id) = auth.uid()
    OR (
      SELECT auth_user_id FROM users WHERE id = (SELECT client_id FROM projects WHERE id = (SELECT project_id FROM conversations WHERE id = messages.conversation_id))
    ) = auth.uid()
    OR (
      SELECT auth_user_id FROM users WHERE id = (SELECT writer_id FROM bids WHERE project_id = (SELECT project_id FROM conversations WHERE id = messages.conversation_id) LIMIT 1)
    ) = auth.uid()
  );

-------------------------------
-- Portfolio items & attachments
-------------------------------
CREATE TABLE IF NOT EXISTS portfolio_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  writer_id int NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title text,
  description text,
  url text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS attachments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_type text, -- e.g., 'project','portfolio','message'
  owner_id bigint,
  file_url text,
  file_name text,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE portfolio_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE attachments ENABLE ROW LEVEL SECURITY;

CREATE POLICY IF NOT EXISTS "Insert portfolio by writer" ON portfolio_items
  FOR INSERT
  WITH CHECK (
    auth.uid() IS NOT NULL AND (SELECT auth_user_id FROM users WHERE id = portfolio_items.writer_id) = auth.uid()
  );

CREATE POLICY IF NOT EXISTS "Select portfolio public or owner" ON portfolio_items
  FOR SELECT
  USING (
    true
  );

-------------------------------
-- Tags & writer_skills
-------------------------------
CREATE TABLE IF NOT EXISTS tags (
  id serial PRIMARY KEY,
  name text UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS writer_skills (
  writer_id int NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  tag_id int NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
  PRIMARY KEY (writer_id, tag_id)
);

ALTER TABLE writer_skills ENABLE ROW LEVEL SECURITY;
CREATE POLICY IF NOT EXISTS "Manage own skills" ON writer_skills
  FOR ALL
  USING ((SELECT auth_user_id FROM users WHERE id = writer_skills.writer_id) = auth.uid())
  WITH CHECK ((SELECT auth_user_id FROM users WHERE id = writer_skills.writer_id) = auth.uid());

-------------------------------
-- Notifications
-------------------------------
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'notif_type') THEN
    CREATE TYPE notif_type AS ENUM ('message','bid','project','system');
  END IF;
END$$;

CREATE TABLE IF NOT EXISTS notifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id int NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  type notif_type NOT NULL,
  payload jsonb,
  is_read boolean DEFAULT false,
  created_at timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_notifications_user ON notifications (user_id);

ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
CREATE POLICY IF NOT EXISTS "Select own notifications" ON notifications
  FOR SELECT
  USING ((SELECT auth_user_id FROM users WHERE id = notifications.user_id) = auth.uid());
CREATE POLICY IF NOT EXISTS "Insert notification by system" ON notifications
  FOR INSERT
  WITH CHECK (auth.role() = 'admin' OR auth.uid() IS NOT NULL); -- adjust as needed

-------------------------------
-- Helpful indexes
-------------------------------
CREATE INDEX IF NOT EXISTS idx_projects_status ON projects (status);
CREATE INDEX IF NOT EXISTS idx_bids_accepted ON bids (accepted);

-------------------------------
-- Seed example rows (safe defaults) - adjust before running in production
-------------------------------
-- NOTE: Prefer creating the admin via Supabase Auth, then update the users row to link `auth_user_id`.
-- Example insert (if you don't yet have an Auth user):
-- INSERT INTO users (role, name, email, phone, password, is_active, created_at)
-- VALUES ('admin', 'Brian Webs', 'websitesbrian585@gmail.com', NULL, NULL, 1, now());

-- After creating the Supabase Auth user, set auth_user_id:
-- UPDATE users SET auth_user_id = '<SUPABASE_AUTH_USER_UUID>' WHERE email = 'websitesbrian585@gmail.com';

-- End of schema
