#!/usr/bin/env bash
# Helper to create assets/config.js from environment variables
# Usage: SUPABASE_URL=... SUPABASE_ANON_KEY=... ./scripts/create_config.sh

if [ -z "$SUPABASE_URL" ] || [ -z "$SUPABASE_ANON_KEY" ]; then
  echo "Set SUPABASE_URL and SUPABASE_ANON_KEY environment vars before running."
  exit 1
fi

cat > assets/config.js <<EOF
// Auto-generated by scripts/create_config.sh - do not commit real keys.
window.APP_CONFIG = {
  SUPABASE_URL: "$SUPABASE_URL",
  SUPABASE_ANON_KEY: "$SUPABASE_ANON_KEY",
  ADMIN_EMAILS: ["websitesbrian585@gmail.com"]
};
EOF

echo "assets/config.js created — do not commit this file if it contains secrets."
